get_filename_component(BUTIANYUN_ALPACA_DIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)

find_path(BUTIANYUN_ALPACA_INCLUDE_DIR butianyun_alpaca_common_api.h ${BUTIANYUN_ALPACA_DIR}/include)
find_library(BUTIANYUN_ALPACA_LIBRARY NAMES butianyun-alpaca PATHS ${BUTIANYUN_ALPACA_DIR}/lib)
if (BUTIANYUN_ALPACA_INCLUDE_DIR AND BUTIANYUN_ALPACA_LIBRARY)
	set(BUTIANYUN_ALPACA_FOUND true)
endif (BUTIANYUN_ALPACA_INCLUDE_DIR AND BUTIANYUN_ALPACA_LIBRARY)