#if !defined(BUTIANYUN_ALPACA_COMMON_API_H)
#define BUTIANYUN_ALPACA_COMMON_API_H

#include <QtGlobal>

#if defined(BUTIANYUN_ALPACA_COMMON_API_EXPORTS)
#define BUTIANYUN_ALPACA_COMMON_API  Q_DECL_EXPORT
#else
#define BUTIANYUN_ALPACA_COMMON_API  Q_DECL_IMPORT
#endif

#endif //BUTIANYUN_ALPACA_COMMON_API_H
